######################## default configuration ####################
baseURL = "http://bonvivant.garden/"
title = "Bon Vivant Garden"
#theme = "bigspring"

# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45

defaultContentLanguage = "fr"
disableLanguages = ["de"]
copyright = "Philippe Tarbouriech / Bon Vivant Garden"

# unsafe html
[markup.goldmark.renderer]
unsafe = true
