[de]
contentDir = "content/de"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Garten"
footer_menu_right = "Support"
languageName = "Deutsch"
title = "Bon Vivant Garden"
weight = 3
[en]
contentDir = "content/en"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Pick your own vegetables and fruits in a network of local forest-gardens."
footer_menu_left = "Company"
footer_menu_middle = "Garden"
footer_menu_right = "Support"
languageName = "English"
title = "Bon Vivant Garden"
weight = 2
[fr]
contentDir = "content/fr"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Cueillir soi-même ses légumes et fruits dans un réseau de jardins-forêts de proximité."
footer_menu_left = "Entreprise"
footer_menu_middle = "Jardin"
footer_menu_right = "Support"
languageName = "Français"
title = "Bon Vivant Garden"
weight = 1
