---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: FR
- type: document
  path: exampleSite/data/fr/homepage.yml
  label: Homepage Data fr
- type: document
  path: exampleSite/content/fr/blog/_index.md
  label: Blog page
- type: directory
  path: exampleSite/content/fr/blog
  label: Blog Post
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: document
  path: exampleSite/content/fr/faq/_index.md
  label: FAQ
- type: directory
  path: exampleSite/content/fr
  label: All Pages
  create: all
  match: "**/*"
- type: document
  path: exampleSite/content/fr/terms-conditions/_index.md
  label: Terms & Conditions
- type: document
  path: exampleSite/content/fr/privacy-policy/_index.md
  label: Privacy Policy
- type: document
  path: exampleSite/content/fr/contact/_index.md
  label: Contact
- type: document
  path: exampleSite/content/fr/pricing/_index.md
  label: Pricing
- type: heading
  label: EN
- type: document
  path: exampleSite/data/en/homepage.yml
  label: Homepage Data en
- type: document
  path: exampleSite/content/en/blog/_index.md
  label: Blog Page
- type: directory
  path: exampleSite/content/en/blog
  label: Blog Post
  create: all
  match: "**/*"
  exclude: _index.md
- type: document
  path: exampleSite/content/en/faq/_index.md
  label: FAQ
- type: directory
  path: exampleSite/content/en
  label: All pages
  create: all
  match: "**/*"
- type: heading
  label: DE
- type: document
  path: exampleSite/data/de/homepage.yml
  label: Homepage Data de
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content
  label: All Pages
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config.toml
  label: Configuration
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
