baseURL = "http://bonvivant.garden/"
copyright = "Copyright Philippe Tarbouriech"
defaultContentLanguage = "fr"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Bon Vivant Garden"
[languages.de]
contentDir = "content/de"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Garten"
footer_menu_right = "Support"
languageName = "De"
title = "Bon Vivant Garden"
weight = 2
[languages.en]
contentDir = "content/en"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Pick your own vegetables and fruits in a network of local forest-gardens."
footer_menu_left = "Company"
footer_menu_middle = "Garden"
footer_menu_right = "Support"
languageName = "En"
title = "Bon Vivant Garden"
weight = 2
[languages.fr]
contentDir = "content/fr"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Cueillir soi-même ses légumes et fruits dans un réseau de jardins-forêts de proximité."
footer_menu_left = "Entreprise"
footer_menu_middle = "Jardin"
footer_menu_right = "Support"
languageName = "Fr"
title = "Bon Vivant Garden"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
name = "Pricing"
url = "pricing"
weight = 1
[[menu.footer_left]]
name = "Quick Start"
url = "#"
weight = 2
[[menu.footer_left]]
name = "About Us"
url = "#"
weight = 3
[[menu.footer_middle]]
name = "Features"
url = "#"
weight = 1
[[menu.footer_middle]]
name = "Platform"
url = "#"
weight = 2
[[menu.footer_middle]]
name = "Pricing"
url = "pricing"
weight = 3
[[menu.footer_right]]
name = "FAQ"
url = "faq"
weight = 1
[[menu.footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
weight = 2
[[menu.footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 3
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "94px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-pinterest"
link = "https://pin.it/1FiIIpt"
title = "Pinterest"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/bonvivantgarden/"
title = "Instagram"
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
