baseURL = "http://bonvivant.garden/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Bon Vivant Garden"
copyright = "Copyright Philippe Tarbouriech"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
disableLanguages = ["de"]

[languages.de]
contentDir = "content/de"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Garten"
footer_menu_right = "Support"
languageName = "De"
title = "Bon Vivant Garden"
weight = 2
[languages.en]
contentDir = "content/en"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Pick your own vegetables and fruits in a network of local forest-gardens."
footer_menu_left = "Company"
footer_menu_middle = "Garden"
footer_menu_right = "Support"
languageName = "En"
title = "Bon Vivant Garden"
weight = 2
[languages.fr]
contentDir = "content/fr"
copyright = "Design [phitar](https://phitar.com/)"
footer_content = "Cueillir soi-même ses légumes et fruits dans un réseau de jardins-forêts de proximité."
footer_menu_left = "Entreprise"
footer_menu_middle = "Jardin"
footer_menu_right = "Support"
languageName = "Fr"
title = "Bon Vivant Garden"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
name = "About Us"
url = "#"
[[menu.footer_left]]
name = "Quick Start"
url = "#"
[[menu.footer_left]]
name = "Garden"
url = "garden"
[[menu.footer_middle]]
name = "Garden"
url = "garden"
[[menu.footer_middle]]
name = "Platform"
url = "#"
[[menu.footer_middle]]
name = "Features"
url = "#"
[[menu.footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[menu.footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[menu.footer_right]]
name = "FAQ"
url = "faq"
[[languages.fr.menu.main]]
name = "BLOG"
url = "blog"
weight = 1
[[languages.fr.menu.main]]
name = "JARDINS"
url = "garden"
weight = 2
[[languages.fr.menu.main]]
name = "CONTACT"
url = "contact"
weight = 3
[[languages.fr.menu.main]]
name = "FAQ"
url = "faq"
weight = 4
[[languages.en.menu.main]]
name = "BLOG"
url = "blog"
weight = 1
[[languages.en.menu.main]]
name = "GARDEN"
url = "garden"
weight = 2
[[languages.en.menu.main]]
name = "CONTACT"
url = "contact"
weight = 3
[[languages.en.menu.main]]
name = "FAQ"
url = "faq"
weight = 4
[[languages.de.menu.main]]
name = "BLOG"
url = "blog"
weight = 1
[[languages.de.menu.main]]
name = "GARTEN"
url = "garden"
weight = 2
[[languages.de.menu.main]]
name = "KONTAKT"
url = "contact"
weight = 3
[[languages.de.menu.main]]
name = "FAQ"
url = "faq"
weight = 4
[params]
author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
logo = "images/logo.svg"
logo_width = "94px"
[languages.en.params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[languages.fr.params.navigation_button]
enable = true
label = "Commencer"
link = "contact"
[languages.de.params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-pinterest"
link = "https://pin.it/1FiIIpt"
title = "Pinterest"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/bonvivantgarden/"
title = "Instagram"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
